# Generated by Django 6.0.6 on 2026-06-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=45)),
                ('apellido_cliente', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=45)),
                ('apellido_empleado', models.CharField(max_length=45)),
                ('rol', models.CharField(max_length=9)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=45)),
                ('fecha_emision', models.DateField()),
                ('total', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('iva', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=45)),
                ('apellido_proveedor', models.CharField(max_length=45)),
                ('telefono_proveedor', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_factura', models.CharField(blank=True, max_length=45, null=True)),
                ('unidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('precio', models.FloatField()),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.factura')),
            ],
            options={
                'db_table': 'detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='Personalizacion',
            fields=[
                ('id_personalizacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.cliente')),
            ],
            options={
                'db_table': 'personalizacion',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=45)),
                ('total', models.FloatField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.empleado')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.venta'),
        ),
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id_camisa', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('marca', models.CharField(max_length=25)),
                ('talla', models.CharField(max_length=10)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.cliente')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.proveedor')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.venta')),
            ],
            options={
                'db_table': 'camisa',
            },
        ),
    ]
